pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                script {
                    // Clone the repository without checking out files initially
                    bat '''
                        git clone --no-checkout https://github.com/isrkan/DevOps-MLOps-Practice.git
                        cd DevOps-MLOps-Practice

                        # Initialize sparse-checkout with cone mode for better performance
                        git sparse-checkout init --cone

                        # Set the specific folder path for sparse checkout
                        git sparse-checkout set "DevOps/Jenkins/Local_deployment_pipeline/Spring Boot/expenses"

                        # Fetch and pull changes from the remote repository
                        git fetch
                        git pull

                        # Update the working directory to match the index
                        git read-tree -mu HEAD
                    '''
                }
            }
        }
    }
}