# Generated by Django 4.2.14 on 2024-07-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = []
