# Deployment configuration file for Kubernetes and is used to create and manage the application pods. This file is used to describe a desired state for the application that Kubernetes will maintain.
apiVersion: apps/v1  # Specifies the API version
kind: Deployment  # Indicates that this is a deployment object
metadata:
  name: expenses-deployment  # Name of the deployment
  labels:
    app: expenses  # Label to identify the app
spec:
  replicas: 2  # Number of pod replicas to run
  selector:
    matchLabels:
      app: expenses  # Selector to identify the pods managed by this deployment
  template:
    metadata:
      labels:
        app: expenses  # Label for the pods
    spec:
      containers:
        - name: expenses  # Name of the container
          image:  expenses:1.0  # Use the local image or an image from docker hub
          ports:
            - containerPort: 8080  # Port the container listens on
          env:  # Environment variables for the container
            - name: SPRING_PROFILES_ACTIVE
              value: "development"  # Sets the active Spring profile to 'development'
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/template1?createDatabaseIfNotExist=true"  # Database connection URL
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres1"

---

# Service configuration file for Kubernetes. This file defines how to expose the app pod within the Kubernetes cluster, allowing other pods to communicate with it.
apiVersion: v1
kind: Service  # Indicates that this is a service object
metadata:
  name: expenses-service  # Name of the service
spec:
  type: NodePort  # Service type to expose the service on a specific port. NodePort is used to make the service accessible from outside the cluster on a specific port.
  selector:
    app: expenses  # Selector to identify the pods targeted by this service
  ports:
    - port: 8084  # Port exposed by the service
      targetPort: 8081  # Port on the pod that the service should forward traffic to
      nodePort: 30082 # Specific port on each node to expose the service (or we can let Kubernetes assign automatically)
