global:
  scrape_interval: 10s  # Scrape metrics every 10 seconds

scrape_configs:
  # Scrape Prometheus' own metrics
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape cAdvisor for Docker container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Scrape Django app metrics
  - job_name: 'expenses'
    metrics_path: 'prometheus/metrics'
    static_configs:
      - targets: ['expenses:8003'] # Use the service name in Docker and the internal container port